### PR TITLE
Update ActionBarSherlock version to 4.2.0

### PR DESCRIPTION
**Pull request by ThomasFondrillon**
Issue [#23](https://github.com/a-thomas/androidkickstartr/issues/23)

### CODE REVIEW

**Comment by a-thomas** [comment]
Thanks! Just before testing your changes. Did you try to import some generated projects based on ABS in Eclipse?

**Comment by ThomasFondrillon** [comment]
Yes of course. With or without Maven configuration, the `actionbarsherlock` folder is recognized.

**Comment by a-thomas** [comment]
Nice job! It works well ;)

**Comment by a-thomas** [comment]
Fix #23

**Pull request merged**
