### PR TITLE
Robolectric support

### PR DESCRIPTION
**Pull request by jeremiemartinez**
Add Robolectric support. Related #22.

### CODE REVIEW

**Comment by sdhull** [comment]
+1 !!  we were just lamenting this omission at my office.

**Comment by JulianRamirez** [comment]
+1!

**Comment by jeremiemartinez** [comment]
I guess it should come soon ;)

**Comment by a-thomas** [comment]
We should probably deploy a new version next week. I hope this feature will be integrated into it.
Stay tuned ;)

**Comment by sdhull** [comment]
Excellent!  Really glad to see you guys are actively working on it!  I
really like it, since the boilerplate setup for a lot of this stuff is
rather frustrating.  :smile:

**Comment by JulianRamirez** [comment]
Very cool. Thanks for the quick turnaround!

**Comment by a-thomas** [comment]
Merged into dev branch. See 8e7f8a0d8a2ae778abba58ff8f220df0a6189d24 

There is a small bug to fix before merging it into the master. I created an issue (#74).

**Pull request closed without merging**
